### ISSUE TITLE
Error! 0: null 

### ISSUE THREAD

**Issue by KhanMaytok** [efeiefei/node-file-manager#1]
I have an error when try upload to a subfolder. 

´´´
2016-01-23T11:10:11-0500 <error> tools.js:16 (Object.module.exports.handelError) Error: Request aborted
    at IncomingMessage.onReqAborted (/home/ubuntu/node_apps/node-file-manager/node_modules/multiparty/index.js:175:17)
    at emitNone (events.js:67:13)
    at IncomingMessage.emit (events.js:166:7)
    at abortIncoming (_http_server.js:280:11)
    at Socket.serverSocketCloseListener (_http_server.js:293:5)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at TCP._onclose (net.js:469:12)

  Error: Request aborted
      at IncomingMessage.onReqAborted (/home/ubuntu/node_apps/node-file-manager/node_modules/multiparty/index.js:175:17)
      at emitNone (events.js:67:13)
      at IncomingMessage.emit (events.js:166:7)
      at abortIncoming (_http_server.js:280:11)
      at Socket.serverSocketCloseListener (_http_server.js:293:5)
      at emitOne (events.js:82:20)
      at Socket.emit (events.js:169:7)
      at TCP._onclose (net.js:469:12)
´´´

The issue is replicated in Windows and Linux.
Used second metod of installation (git clone)

**Comment by dunice-kuzmenko** [comment]
I also have this problem. On all methods of installation
node ver 4.2.2

**Comment by dunice-kuzmenko** [comment]
Ok, i think - i fixed this

**Comment by KhanMaytok** [comment]
:+1:

**Comment by efeiefei** [comment]
Maybe because of the co-multiparty can only handle small files.
I have merged @dunice-kuzmenko ‘s commit and looks useful. Thanks a lot.
