### ISSUE TITLE
Large file upload fails

### ISSUE THREAD

**Issue by jamesmgittins** [efeiefei/node-file-manager#12]
Running it from my windows desktop I can upload a file as large as 500MB before it fails but anything bigger than that and I get an error message

![screen shot 2016-09-08 at 10 47 53](https://cloud.githubusercontent.com/assets/9380190/18345094/d0bd38fc-75b1-11e6-968a-6c90f08cba6c.png)

Running on a raspberry pi 3 with more limited resources it fails with anything larger than about 70MB

**Comment by songbaoqiang** [comment]
coding your uploading function

**Comment by songbaoqiang** [comment]
error in incoming_form.js 

Error: Request aborted
      at IncomingMessage.<anonymous> (/var/www/ffmlive/file-manager/node_modules/formidable/lib/incoming_form.js:120:19)
      at emitNone (events.js:86:13)
      at IncomingMessage.emit (events.js:185:7)
      at abortIncoming (_http_server.js:280:11)
      at Socket.serverSocketCloseListener (_http_server.js:293:5)
      at emitOne (events.js:101:20)
      at Socket.emit (events.js:188:7)
      at TCP._handle.close [as _onclose](net.js:493:12)

**Comment by songbaoqiang** [comment]
timeout  setting !!!

**Comment by efeiefei** [comment]
Sorry @jamesmgittins 
Recently, I do not have the energy to add "large file" features.

**Comment by circuitry2** [comment]
@efeiefei what work is needed to allow larger files to be uploaded?

**Comment by corningsun** [comment]
@circuitry2 
you can modified the http timeout settings in file `node-file-manager/lib/public/js/app.js`

![image](https://user-images.githubusercontent.com/11749559/36518369-0456cde4-177e-11e8-8e4b-25527458183a.png)
