### ISSUE TITLE
Unexpected identifier

### ISSUE THREAD

**Issue by ashishdoneriya** [efeiefei/node-file-manager#6]
/usr/local/lib/node_modules/node-file-manager/node_modules/koa/node_modules/composition/index.js:116
  return yield Promise.resolve(promise);
               ^^^^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/node-file-manager/node_modules/koa/lib/application.js:10:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by efeiefei** [comment]
you should use node version > 0.11
and `node --harmony index.js`
